declare const styles: {
    readonly 'icon-item-AI拓展伺服器': string
    readonly 'icon-item-AI限制器': string
    readonly 'icon-item-FICSIT兑换券': string
    readonly 'icon-item-F金三角': string
    readonly 'icon-item-F金锭': string
    readonly 'icon-item-SAM物质': string
    readonly 'icon-item-SAM物质波波动器': string
    readonly 'icon-item-二氧化硅': string
    readonly 'icon-item-二氧化硅溶解液': string
    readonly 'icon-item-信标': string
    readonly 'icon-item-冷却系统': string
    readonly 'icon-item-压缩煤': string
    readonly 'icon-item-原油': string
    readonly 'icon-item-叠加振荡器': string
    readonly 'icon-item-固态生物燃料': string
    readonly 'icon-item-塑料': string
    readonly 'icon-item-复合铝板': string
    readonly 'icon-item-外星DNA胶囊': string
    readonly 'icon-item-外星生物蛋白质': string
    readonly 'icon-item-外星能量矩阵': string
    readonly 'icon-item-多功能框架': string
    readonly 'icon-item-奇点电池': string
    readonly 'icon-item-定子': string
    readonly 'icon-item-封压方块': string
    readonly 'icon-item-封装钚棒': string
    readonly 'icon-item-封装铀棒': string
    readonly 'icon-item-弹道跃迁引擎': string
    readonly 'icon-item-强化铁板': string
    readonly 'icon-item-彩色子弹': string
    readonly 'icon-item-急速电线': string
    readonly 'icon-item-散射铁棒弹': string
    readonly 'icon-item-散热器': string
    readonly 'icon-item-无烟火药': string
    readonly 'icon-item-无线电控制单元': string
    readonly 'icon-item-时间水晶': string
    readonly 'icon-item-晶体振荡器': string
    readonly 'icon-item-智能嵌板': string
    readonly 'icon-item-暗物质晶体': string
    readonly 'icon-item-暗物质残渣': string
    readonly 'icon-item-木材': string
    readonly 'icon-item-树叶': string
    readonly 'icon-item-核子诺氏雷筒': string
    readonly 'icon-item-核意面': string
    readonly 'icon-item-桶装原油': string
    readonly 'icon-item-桶装氧化铝溶液': string
    readonly 'icon-item-桶装水': string
    readonly 'icon-item-桶装涡轮燃油': string
    readonly 'icon-item-桶装液态生物燃料': string
    readonly 'icon-item-桶装火箭燃料': string
    readonly 'icon-item-桶装燃油': string
    readonly 'icon-item-桶装电离燃油': string
    readonly 'icon-item-桶装硝酸': string
    readonly 'icon-item-桶装硫酸': string
    readonly 'icon-item-桶装重油残渣': string
    readonly 'icon-item-模块化引擎': string
    readonly 'icon-item-模块化框架': string
    readonly 'icon-item-橡胶': string
    readonly 'icon-item-步枪弹药': string
    readonly 'icon-item-毒气诺石': string
    readonly 'icon-item-气体过滤器': string
    readonly 'icon-item-氧化铝溶液': string
    readonly 'icon-item-氮气': string
    readonly 'icon-item-水': string
    readonly 'icon-item-油焦': string
    readonly 'icon-item-活性SAM物质': string
    readonly 'icon-item-涡轮步枪弹': string
    readonly 'icon-item-涡轮燃油': string
    readonly 'icon-item-涡轮马达': string
    readonly 'icon-item-液态生物燃料': string
    readonly 'icon-item-混凝土': string
    readonly 'icon-item-激发态光子物质': string
    readonly 'icon-item-火箭燃料': string
    readonly 'icon-item-热能推进火箭': string
    readonly 'icon-item-焊接模块化框架': string
    readonly 'icon-item-煤': string
    readonly 'icon-item-燃料': string
    readonly 'icon-item-爆炸铁棒弹': string
    readonly 'icon-item-瓶装氮气': string
    readonly 'icon-item-生化塑造器': string
    readonly 'icon-item-生物质': string
    readonly 'icon-item-电击铁棒弹': string
    readonly 'icon-item-电池': string
    readonly 'icon-item-电磁控制杆': string
    readonly 'icon-item-电离燃油': string
    readonly 'icon-item-电线': string
    readonly 'icon-item-电缆': string
    readonly 'icon-item-电路板': string
    readonly 'icon-item-石灰石': string
    readonly 'icon-item-石英晶体': string
    readonly 'icon-item-硝酸': string
    readonly 'icon-item-硫磺': string
    readonly 'icon-item-硫酸': string
    readonly 'icon-item-碎铝渣': string
    readonly 'icon-item-碘化过滤器': string
    readonly 'icon-item-磁场发生器': string
    readonly 'icon-item-神经量子处理器': string
    readonly 'icon-item-空桶': string
    readonly 'icon-item-空瓶': string
    readonly 'icon-item-粗石英': string
    readonly 'icon-item-紫色能量蛞蝓': string
    readonly 'icon-item-纤维织物': string
    readonly 'icon-item-组装编导系统': string
    readonly 'icon-item-聚合树脂': string
    readonly 'icon-item-能量碎片': string
    readonly 'icon-item-脉冲诺石': string
    readonly 'icon-item-自动线路': string
    readonly 'icon-item-自适应控制单元': string
    readonly 'icon-item-花瓣': string
    readonly 'icon-item-菌丝体': string
    readonly 'icon-item-蓝色能量蛞蝓': string
    readonly 'icon-item-螺丝': string
    readonly 'icon-item-计算机': string
    readonly 'icon-item-诺氏雷筒': string
    readonly 'icon-item-超级计算机': string
    readonly 'icon-item-转子': string
    readonly 'icon-item-追踪步枪弹': string
    readonly 'icon-item-重型模块化框架': string
    readonly 'icon-item-重油残渣': string
    readonly 'icon-item-钚丸': string
    readonly 'icon-item-钚废料': string
    readonly 'icon-item-钚燃料棒': string
    readonly 'icon-item-钢梁': string
    readonly 'icon-item-钢筋混凝土梁': string
    readonly 'icon-item-钢管': string
    readonly 'icon-item-钢锭': string
    readonly 'icon-item-钦金矿石': string
    readonly 'icon-item-钦金锭': string
    readonly 'icon-item-钻石': string
    readonly 'icon-item-铀': string
    readonly 'icon-item-铀废料': string
    readonly 'icon-item-铀燃料棒': string
    readonly 'icon-item-铁板': string
    readonly 'icon-item-铁棒': string
    readonly 'icon-item-铁棒弹': string
    readonly 'icon-item-铁矿石': string
    readonly 'icon-item-铁锭': string
    readonly 'icon-item-铜板': string
    readonly 'icon-item-铜矿石': string
    readonly 'icon-item-铜粉': string
    readonly 'icon-item-铜锭': string
    readonly 'icon-item-铝制外壳': string
    readonly 'icon-item-铝土矿': string
    readonly 'icon-item-铝锭': string
    readonly 'icon-item-镄': string
    readonly 'icon-item-镄燃料棒': string
    readonly 'icon-item-集束诺氏雷筒': string
    readonly 'icon-item-非裂变贫铀': string
    readonly 'icon-item-马达': string
    readonly 'icon-item-高速连接器': string
    readonly 'icon-item-黄色能量蛞蝓': string
    readonly 'icon-item-黑火药': string
    readonly 'iconitem-': string
}
export = styles
